import { Fragment } from 'react';
import Head from 'next/head';
import Header from "@/app/components/Header";
import Footer from "@/app/components/Footer";

export const metadata = {
    title: 'Blog App',
    description: 'Generated by create next app',
}

export default function Layout({ children }) {
    return (
        <Fragment>
            <Head>
                <meta charSet="utf-8" />
                <meta name="viewport" content="width=device-width, initial-scale=1.0" />
                <meta name="description" content={metadata.description} />
                <meta name="keywords" content={metadata.keywords} />
                <title>{metadata.title}</title>
                {/* Your other head elements (meta tags, links, etc.) */}
            </Head>
            <Header />
            {children}
            <Footer />
        </Fragment>
    );
}
