import Head from 'next/head';
import Header from "@/app/components/Header";
import Footer from "@/app/components/Footer";

export const metadata = {
  title: 'Blog App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
        <Head>
            <meta charSet="utf-8" />
            <meta name="viewport" content="width=device-width, initial-scale=1.0" />
            <title>ZenBlog Bootstrap Template - Index</title>
            <meta name="description" content="" />
            <meta name="keywords" content="" />

            {/* Favicons */}
            <link rel="icon" href="/assets/img/favicon.png" />
            <link rel="apple-touch-icon" href="/assets/img/apple-touch-icon.png" />

            {/* Google Fonts */}
            <link rel="preconnect" href="https://fonts.googleapis.com" />
            <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
            <link href="https://fonts.googleapis.com/css2?family=EB+Garamond:wght@400;500&family=Inter:wght@400;500&family=Playfair+Display:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet" />

            {/* Vendor CSS Files */}
            <link rel="stylesheet" href="/assets/vendor/bootstrap/css/bootstrap.min.css" />
            <link rel="stylesheet" href="/assets/vendor/bootstrap-icons/bootstrap-icons.css" />
            <link rel="stylesheet" href="/assets/vendor/swiper/swiper-bundle.min.css" />
            <link rel="stylesheet" href="/assets/vendor/glightbox/css/glightbox.min.css" />
            <link rel="stylesheet" href="/assets/vendor/aos/aos.css" />

            {/* Template Main CSS Files */}
            <link rel="stylesheet" href="/assets/css/variables.css" />
            <link rel="stylesheet" href="/assets/css/main.css" />
        </Head>
        <body>
            <Header/>
            {children}
            <Footer/>
        <a href="#" className="scroll-top d-flex align-items-center justify-content-center"><i className="bi bi-arrow-up-short"></i></a> 
        <script src="/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
        <script src="/assets/vendor/swiper/swiper-bundle.min.js"></script>
        <script src="/assets/vendor/glightbox/js/glightbox.min.js"></script>
        <script src="/assets/vendor/aos/aos.js"></script>
        <script src="/assets/vendor/php-email-form/validate.js"></script> 
        <script src="/assets/js/main.js"></script>
        </body>
        </html>
    )
}
